export const START_SEARCH = 'START_SEARCH';
export const FETCH_ARTISTS_START = 'FETCH_ARTISTS_START';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAILURE = 'FETCH_ARTISTS_FAILURE';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

export const RESET_SEARCH = 'RESET_SEARCH';
